# Directories
dir_logs:
dir_dls:
dir_vault:
dir_boxroom:
dir_tmp:
dir_packages:

# Files
file_sync:
file_exclusion:

# Whitelisted directories (won't be moved)
white_dirs:
  - video
  - img
  - audio
  - archff
  - binaries
  - data
  - clasificar
  - baul

# Boxroom directories (for classification)
boxroom:
  - name: video
    filetypes: [avi, mpg]
  - name: img
    filetypes: [jpg]
  - name: audio
    filetypes: [mp3, ogg]
  - name: archff
    filetypes: [zip, rar]
  - name: binaries
    filetypes: [exe]
  - name: data
    filetypes: [pdf]

box_misc: clasificar

# Parameters
days_old: 15 # move files older than this time in days

# Archives (zipped files)

archives:
  - name:
    paths:
      - 